# Use an official base image with C/C++ development
FROM debian:latest

# Install necessary packages and tools
RUN apt-get update && apt-get install -y \
  build-essential autoconf libtool pkg-config \
  libgflags-dev libgtest-dev clang libc++-dev \
  git protobuf-compiler libprotobuf-dev

# Copy app directory over
COPY ../ /nucleobits-backend
WORKDIR /nucleobits-backend

RUN ls -la

